But if passeed an Unsigned 64 bits integer you get:
NotImplementedError: variable ``N`` refers to a 64-bit unsigned
integer column, not yet supported in conditions, sorry; please use
regular Python selections

Of course, that type cannot be upcasted to any of the listed, so you
trully cannot expect it to work; but the behaviour is not exactly what
it says on the paragraph.