setup.py: gracefuly handle cpuinfo failure
When comping on aarch64, setup.py fails with:
Exception: py-cpuinfo currently only works on X86 and some ARM CPUs.
Assume that the CPU does not support SSE2 or AVX in importing cpuinfo fails
and continue.

(Package builds fine and tests pass with this patch:
https://kojipkgs.fedoraproject.org//packages/python-tables/3.3.0/1.fc26/data/logs/aarch64/build.log)