FIX: Pass `refcheck=False` to `np.ndarray.resize()` for PyPy compat
Pass `refcheck=False` when resizing an `np.ndarray` in place, in order
to fix a test failure on PyPy3:

```
Traceback (most recent call last):
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 266, in test_write_chunk_missing1
    return self._test_write_chunk_missing(shrink_after=False)
  File "/tmp/PyTables/tables/tests/test_direct_chunk.py", line 255, in _test_write_chunk_missing
    new_obj.resize(self.array.shape)
ValueError: cannot resize an array with refcheck=True on PyPy.
Use the np.resize function or refcheck=False
```

Since the object is created immediately above the `.resize()` call,
adding `refcheck=False` should be entirely safe.  Furthermore,
unlike `np.resize()` this preserves the current behavior when new shape
is larger than the original.

Fixes #1202