Python3 Unicode string support in Atom.from_dtype
In Python3 strings show up as dtype e.g. '<U50'. The current code only looks for a Python2-style 'S'-kind, resulting in
    ValueError: unknown type: 'str1600'
upon calling e.g. create_array with a string array as obj= argument, since this case currently gets handed over to from_type